//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataAnnotationsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAnnotationsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Entities.Resources.DataAnnotationsResources", typeof(DataAnnotationsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active in duration.
        /// </summary>
        internal static string ActiveInDuration {
            get {
                return ResourceManager.GetString("ActiveInDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Diploma.
        /// </summary>
        internal static string AdvancedDiploma {
            get {
                return ResourceManager.GetString("AdvancedDiploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aged Care.
        /// </summary>
        internal static string AgedCare {
            get {
                return ResourceManager.GetString("AgedCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        internal static string AppLink {
            get {
                return ResourceManager.GetString("AppLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate Degree.
        /// </summary>
        internal static string AssociateDegree {
            get {
                return ResourceManager.GetString("AssociateDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string AUDollar {
            get {
                return ResourceManager.GetString("AUDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor Degree.
        /// </summary>
        internal static string BachelorDegree {
            get {
                return ResourceManager.GetString("BachelorDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor Honours Degree.
        /// </summary>
        internal static string BachelorHonoursDegree {
            get {
                return ResourceManager.GetString("BachelorHonoursDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        internal static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Image.
        /// </summary>
        internal static string BodyImage {
            get {
                return ResourceManager.GetString("BodyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builted.
        /// </summary>
        internal static string Builted {
            get {
                return ResourceManager.GetString("Builted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bushfire Shelter.
        /// </summary>
        internal static string BushfireShelter {
            get {
                return ResourceManager.GetString("BushfireShelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafe.
        /// </summary>
        internal static string Cafe {
            get {
                return ResourceManager.GetString("Cafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarParks.
        /// </summary>
        internal static string CarParks {
            get {
                return ResourceManager.GetString("CarParks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate I.
        /// </summary>
        internal static string CertificateI {
            get {
                return ResourceManager.GetString("CertificateI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate II.
        /// </summary>
        internal static string CertificateII {
            get {
                return ResourceManager.GetString("CertificateII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate III.
        /// </summary>
        internal static string CertificateIII {
            get {
                return ResourceManager.GetString("CertificateIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate IV.
        /// </summary>
        internal static string CertificateIV {
            get {
                return ResourceManager.GetString("CertificateIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 1.
        /// </summary>
        internal static string Class1 {
            get {
                return ResourceManager.GetString("Class1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 10.
        /// </summary>
        internal static string Class10 {
            get {
                return ResourceManager.GetString("Class10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 10a.
        /// </summary>
        internal static string Class10a {
            get {
                return ResourceManager.GetString("Class10a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 10b.
        /// </summary>
        internal static string Class10b {
            get {
                return ResourceManager.GetString("Class10b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 10c.
        /// </summary>
        internal static string Class10c {
            get {
                return ResourceManager.GetString("Class10c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 1a.
        /// </summary>
        internal static string Class1a {
            get {
                return ResourceManager.GetString("Class1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 1b.
        /// </summary>
        internal static string Class1b {
            get {
                return ResourceManager.GetString("Class1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 2.
        /// </summary>
        internal static string Class2 {
            get {
                return ResourceManager.GetString("Class2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 3.
        /// </summary>
        internal static string Class3 {
            get {
                return ResourceManager.GetString("Class3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 4.
        /// </summary>
        internal static string Class4 {
            get {
                return ResourceManager.GetString("Class4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 5.
        /// </summary>
        internal static string Class5 {
            get {
                return ResourceManager.GetString("Class5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 6.
        /// </summary>
        internal static string Class6 {
            get {
                return ResourceManager.GetString("Class6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 7.
        /// </summary>
        internal static string Class7 {
            get {
                return ResourceManager.GetString("Class7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 7a.
        /// </summary>
        internal static string Class7a {
            get {
                return ResourceManager.GetString("Class7a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 7b.
        /// </summary>
        internal static string Class7b {
            get {
                return ResourceManager.GetString("Class7b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 8.
        /// </summary>
        internal static string Class8 {
            get {
                return ResourceManager.GetString("Class8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 9.
        /// </summary>
        internal static string Class9 {
            get {
                return ResourceManager.GetString("Class9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 9a.
        /// </summary>
        internal static string Class9a {
            get {
                return ResourceManager.GetString("Class9a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 9b.
        /// </summary>
        internal static string Class9b {
            get {
                return ResourceManager.GetString("Class9b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 9c.
        /// </summary>
        internal static string Class9c {
            get {
                return ResourceManager.GetString("Class9c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        internal static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comapny.
        /// </summary>
        internal static string Comapny {
            get {
                return ResourceManager.GetString("Comapny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conservation.
        /// </summary>
        internal static string Conservation {
            get {
                return ResourceManager.GetString("Conservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diploma.
        /// </summary>
        internal static string Diploma {
            get {
                return ResourceManager.GetString("Diploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistrictedArea.
        /// </summary>
        internal static string DistrictedArea {
            get {
                return ResourceManager.GetString("DistrictedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctoral Degree.
        /// </summary>
        internal static string DoctoralDegree {
            get {
                return ResourceManager.GetString("DoctoralDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailLink {
            get {
                return ResourceManager.GetString("EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmptyLot.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        internal static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        internal static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing.
        /// </summary>
        internal static string Finishing {
            get {
                return ResourceManager.GetString("Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        internal static string Flash {
            get {
                return ResourceManager.GetString("Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Access.
        /// </summary>
        internal static string FullAccess {
            get {
                return ResourceManager.GetString("FullAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduate Certificate.
        /// </summary>
        internal static string GraduateCertificate {
            get {
                return ResourceManager.GetString("GraduateCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduate Diploma.
        /// </summary>
        internal static string GraduateDiploma {
            get {
                return ResourceManager.GetString("GraduateDiploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Care.
        /// </summary>
        internal static string HealthCare {
            get {
                return ResourceManager.GetString("HealthCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Rise.
        /// </summary>
        internal static string HighRise {
            get {
                return ResourceManager.GetString("HighRise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        internal static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        internal static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        internal static string HTML {
            get {
                return ResourceManager.GetString("HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am.
        /// </summary>
        internal static string IAM {
            get {
                return ResourceManager.GetString("IAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Image.
        /// </summary>
        internal static string IconImage {
            get {
                return ResourceManager.GetString("IconImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive.
        /// </summary>
        internal static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial.
        /// </summary>
        internal static string Industrial {
            get {
                return ResourceManager.GetString("Industrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersex.
        /// </summary>
        internal static string Intersex {
            get {
                return ResourceManager.GetString("Intersex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intstagram.
        /// </summary>
        internal static string Intstagram {
            get {
                return ResourceManager.GetString("Intstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I prefer not to say.
        /// </summary>
        internal static string IPreferNotToSay {
            get {
                return ResourceManager.GetString("IPreferNotToSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPublished does not have value.
        /// </summary>
        internal static string IsPublishedIsNull {
            get {
                return ResourceManager.GetString("IsPublishedIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jails.
        /// </summary>
        internal static string Jails {
            get {
                return ResourceManager.GetString("Jails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labratory.
        /// </summary>
        internal static string Labratory {
            get {
                return ResourceManager.GetString("Labratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string Landscape {
            get {
                return ResourceManager.GetString("Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence.
        /// </summary>
        internal static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn.
        /// </summary>
        internal static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan.
        /// </summary>
        internal static string Loan {
            get {
                return ResourceManager.GetString("Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan help.
        /// </summary>
        internal static string LoanHelp {
            get {
                return ResourceManager.GetString("LoanHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans.
        /// </summary>
        internal static string Loans {
            get {
                return ResourceManager.GetString("Loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan types.
        /// </summary>
        internal static string LoanTypes {
            get {
                return ResourceManager.GetString("LoanTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Rise.
        /// </summary>
        internal static string LowRise {
            get {
                return ResourceManager.GetString("LowRise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masters Degree.
        /// </summary>
        internal static string MastersDegree {
            get {
                return ResourceManager.GetString("MastersDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MastersDegree (Coursework).
        /// </summary>
        internal static string MastersDegreeCoursework {
            get {
                return ResourceManager.GetString("MastersDegreeCoursework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masters Degree (Extended).
        /// </summary>
        internal static string MastersDegreeExtended {
            get {
                return ResourceManager.GetString("MastersDegreeExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MastersDegree (Research).
        /// </summary>
        internal static string MastersDegreeResearch {
            get {
                return ResourceManager.GetString("MastersDegreeResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Rise.
        /// </summary>
        internal static string MediumRise {
            get {
                return ResourceManager.GetString("MediumRise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motel.
        /// </summary>
        internal static string Motel {
            get {
                return ResourceManager.GetString("Motel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiating.
        /// </summary>
        internal static string Negotiating {
            get {
                return ResourceManager.GetString("Negotiating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-binary.
        /// </summary>
        internal static string NonBinary {
            get {
                return ResourceManager.GetString("NonBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offices.
        /// </summary>
        internal static string Offices {
            get {
                return ResourceManager.GetString("Offices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Access.
        /// </summary>
        internal static string PartialAccess {
            get {
                return ResourceManager.GetString("PartialAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnership.
        /// </summary>
        internal static string Partnership {
            get {
                return ResourceManager.GetString("Partnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        internal static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string PersonalID {
            get {
                return ResourceManager.GetString("PersonalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinterest.
        /// </summary>
        internal static string Pinterest {
            get {
                return ResourceManager.GetString("Pinterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing.
        /// </summary>
        internal static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceUnit.
        /// </summary>
        internal static string PriceUnit {
            get {
                return ResourceManager.GetString("PriceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Garage.
        /// </summary>
        internal static string PrivateGarage {
            get {
                return ResourceManager.GetString("PrivateGarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Extension.
        /// </summary>
        internal static string ProjectExtension {
            get {
                return ResourceManager.GetString("ProjectExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reddit.
        /// </summary>
        internal static string Reddit {
            get {
                return ResourceManager.GetString("Reddit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect.
        /// </summary>
        internal static string Redirect {
            get {
                return ResourceManager.GetString("Redirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        internal static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered User.
        /// </summary>
        internal static string RegisteredUser {
            get {
                return ResourceManager.GetString("RegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential Care Building.
        /// </summary>
        internal static string ResidentialCareBuilding {
            get {
                return ResourceManager.GetString("ResidentialCareBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        internal static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        internal static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheds.
        /// </summary>
        internal static string Sheds {
            get {
                return ResourceManager.GetString("Sheds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shops.
        /// </summary>
        internal static string Shops {
            get {
                return ResourceManager.GetString("Shops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        internal static string Skype {
            get {
                return ResourceManager.GetString("Skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapchat.
        /// </summary>
        internal static string Snapchat {
            get {
                return ResourceManager.GetString("Snapchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        internal static string Social_Media {
            get {
                return ResourceManager.GetString("Social Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sole Trader.
        /// </summary>
        internal static string SoleTrader {
            get {
                return ResourceManager.GetString("SoleTrader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        internal static string Static {
            get {
                return ResourceManager.GetString("Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suburb.
        /// </summary>
        internal static string Suburb {
            get {
                return ResourceManager.GetString("Suburb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swimming Pool.
        /// </summary>
        internal static string SwimmingPool {
            get {
                return ResourceManager.GetString("SwimmingPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram.
        /// </summary>
        internal static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Image.
        /// </summary>
        internal static string ThumbnailImage {
            get {
                return ResourceManager.GetString("ThumbnailImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TikTok.
        /// </summary>
        internal static string TikTok {
            get {
                return ResourceManager.GetString("TikTok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Image.
        /// </summary>
        internal static string TitleImage {
            get {
                return ResourceManager.GetString("TitleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town House.
        /// </summary>
        internal static string TownHouse {
            get {
                return ResourceManager.GetString("TownHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transgender.
        /// </summary>
        internal static string Transgender {
            get {
                return ResourceManager.GetString("Transgender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust.
        /// </summary>
        internal static string Trust {
            get {
                return ResourceManager.GetString("Trust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tumblr.
        /// </summary>
        internal static string Tumblr {
            get {
                return ResourceManager.GetString("Tumblr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Construction.
        /// </summary>
        internal static string UnderConstruction {
            get {
                return ResourceManager.GetString("UnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urban.
        /// </summary>
        internal static string Urban {
            get {
                return ResourceManager.GetString("Urban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viber.
        /// </summary>
        internal static string Viber {
            get {
                return ResourceManager.GetString("Viber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villas.
        /// </summary>
        internal static string Villas {
            get {
                return ResourceManager.GetString("Villas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses.
        /// </summary>
        internal static string Warehouses {
            get {
                return ResourceManager.GetString("Warehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string WebsiteLink {
            get {
                return ResourceManager.GetString("WebsiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeChat.
        /// </summary>
        internal static string WeChat {
            get {
                return ResourceManager.GetString("WeChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp.
        /// </summary>
        internal static string WhatsApp {
            get {
                return ResourceManager.GetString("WhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube.
        /// </summary>
        internal static string YouTube {
            get {
                return ResourceManager.GetString("YouTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¥.
        /// </summary>
        internal static string Yuan {
            get {
                return ResourceManager.GetString("Yuan", resourceCulture);
            }
        }
    }
}
